crowbar_register: Fail early if chef-client wasn't installed
This could happen if the repos were not valid, for instance. We do not
want to then post a discovered state for the node.

diff --git a/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb b/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
--- a/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
+++ b/chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
@@ -295,6 +295,12 @@ zypper --non-interactive install --auto-agree-with-licenses suse-sle12-cloud-com
 <% end -%>
 zypper --non-interactive install $PACKAGES_INSTALL
 
+# Fail early if we know we can't succeed because of a missing chef-client
+if ! which chef-client &> /dev/null; then
+  echo "chef-client is not available."
+  exit 1
+fi
+
 
 # Some initial setup
 # ------------------
