Clean up whitespace in crowbar_join.redhat.sh.erb

diff --git a/chef/cookbooks/provisioner/templates/default/crowbar_join.redhat.sh.erb b/chef/cookbooks/provisioner/templates/default/crowbar_join.redhat.sh.erb
--- a/chef/cookbooks/provisioner/templates/default/crowbar_join.redhat.sh.erb
+++ b/chef/cookbooks/provisioner/templates/default/crowbar_join.redhat.sh.erb
@@ -19,7 +19,7 @@ case $1 in
     status) service chef-client status ; exit $? ;;
     start|'') pidof chef-client && exit 0;;
     *) echo "Unknown action to crowbar_join.sh."
-	exit 1;;
+        exit 1;;
 esac
 
 HTTP_SERVER="<%= @admin_ip %>:8091"
@@ -42,17 +42,17 @@ log_to() {
     local __timestamp="$(date '+%F %T %z')"
     shift
     printf "\n%s\n" "$__timestamp: Running $*" | \
-	tee -a "$__log.err" >> "$__log.log"
+        tee -a "$__log.err" >> "$__log.log"
     local _ret=0
     if "$@" 2>> "$__log.err" >>"$__log.log"; then
-	_ret=0
+        _ret=0
     else
-	_ret="$?"
-	echo "$__timestamp: $* failed."
-	echo "See $__log.log and $__log.err for more information."
+        _ret="$?"
+        echo "$__timestamp: $* failed."
+        echo "See $__log.log and $__log.err for more information."
     fi
     printf "\n$s\n--------\n"  "$(date '+%F %T %z'): Done $*" | \
-	tee -a "$__log.err" >> "$__log.log"
+        tee -a "$__log.err" >> "$__log.log"
     return $_ret
 }
 
@@ -85,8 +85,8 @@ sync_time() {
     service ntp stop
     killall ntpd
     while ! /usr/sbin/ntpdate -b $IP; do
-	echo "Waiting for NTP server"
-	sleep 1
+        echo "Waiting for NTP server"
+        sleep 1
     done
 }
 
@@ -94,8 +94,8 @@ sync_time() {
 # delays.
 if ! grep -q '^UseDNS.*no' /etc/ssh/sshd_config; then
     sed -i -e 's/^\(GSSAPI\)/#\1/' \
-	-e 's/#\(UseDNS.*\)yes/\1no/' \
-	/etc/ssh/sshd_config
+        -e 's/#\(UseDNS.*\)yes/\1no/' \
+        /etc/ssh/sshd_config
     service sshd restart
 fi
 
@@ -103,7 +103,7 @@ fi
 rm -f /update_system2.sh
 rm -f /net-post-install.sh
 
-echo "Synchronizing time (pass 1)" 
+echo "Synchronizing time (pass 1)"
 sync_time
 
 # Mark us as readying, and get our cert.
@@ -113,7 +113,7 @@ mkdir -p /etc/chef
 curl -o /etc/chef/validation.pem \
     "http://$HTTP_SERVER/validation.pem"
 
-if [[ ! -x /etc/init.d/bluepill ]]; then 
+if [[ ! -x /etc/init.d/bluepill ]]; then
     # Make sure that the client knows how to talk to the server
     echo "chef_server_url \"http://$IP:4000\"" >/etc/chef/client.rb
 
@@ -121,23 +121,23 @@ if [[ ! -x /etc/init.d/bluepill ]]; then
     echo "Installing Chef..."
 
     while ! log_to yum yum -q -y update ; do
-	echo "Failed to do yum update, wait and try again"
-	sleep 1
+        echo "Failed to do yum update, wait and try again"
+        sleep 1
     done
     while ! log_to yum yum -q -y install rubygem-chef patch libxml2-devel zlib-devel ; do
-	echo "Failed to do yum install, wait and try again"
-	sleep 1
+        echo "Failed to do yum install, wait and try again"
+        sleep 1
     done
 
     # Install ohai patch if needed.
     di=$(find /usr -path '*/ohai-0.6.6/lib/ohai/plugins/linux' -type d)
     [[ $di && -d $di ]] && {
-	curl -o "$di/ohai.patch" \
-	    "http://$HTTP_SERVER/redhat_dvd/extra/patches/ohai-linux-platform.patch"
-	[[ -f $di/ohai.patch ]] && (
-	    cd "$di"
-	    patch -p0 <ohai.patch
-	)
+        curl -o "$di/ohai.patch" \
+            "http://$HTTP_SERVER/redhat_dvd/extra/patches/ohai-linux-platform.patch"
+        [[ -f $di/ohai.patch ]] && (
+            cd "$di"
+            patch -p0 <ohai.patch
+        )
     }
 
     log_to chef service chef-client stop
@@ -177,7 +177,7 @@ case \$1 in
              exit 1
             fi;;
     *) echo "\$1: Not supported.";;
-esac   
+esac
 EOF
     chmod 755 /etc/init.d/bluepill
 fi
@@ -209,7 +209,7 @@ if ! log_to chef chef-client -l debug; then
     echo "Removing Chef Cache"
     rm -rf /var/cache/chef/*
     echo "Running Chef Client (pass 3) - cache cleanup"
-    if ! log_to chef chef-client -l debug; then 
+    if ! log_to chef chef-client -l debug; then
         log_to ifup /sbin/service network restart
         echo "Error Path"
         echo "Syncing Time (pass 4)"
@@ -220,7 +220,7 @@ if ! log_to chef chef-client -l debug; then
         rm -f /etc/chef/client.pem
         post_state $HOSTNAME "hardware-updated"
         echo "Running Chef Client (pass 4) - password cleanup"
-        if ! log_to chef chef-client -l debug; then 
+        if ! log_to chef chef-client -l debug; then
             log_to ifup /sbin/service network restart
             echo "chef-client run failed four times, giving up."
             echo "Failed"
