crowbar_join: Move some code to a function
Everything related to the initial setup is now in a do_setup function.

diff --git a/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb b/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
--- a/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
+++ b/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
@@ -33,10 +33,6 @@ exec 2>>/var/log/crowbar/crowbar_join/errlog
 export PS4='${BASH_SOURCE}@${LINENO}(${FUNCNAME[0]}): '
 set -x
 
-if [[ ! -d /var/log/chef/ ]]; then
-    mkdir -p /var/log/chef/
-fi
-
 if [[ -f /etc/crowbar.install.key ]]; then
     export CROWBAR_KEY="$(cat /etc/crowbar.install.key)"
 fi
@@ -75,6 +71,72 @@ post_state() {
   umask $oldumask
 }
 
+sync_time() {
+    # stop ntpd before we run ntpdate, and start it again afterwards.
+    service ntp stop
+    # Warning! Newer sntp releases use different options (e.g. the one
+    # on openSUSE 12.1
+    while ! sntp -P no -r $IP; do
+	echo "Waiting for NTP server"
+	sleep 1
+    done
+}
+
+do_setup() {
+    mkdir -p /etc/chef
+    curl -o /etc/chef/validation.pem \
+        "http://$HTTP_SERVER/validation.pem"
+
+    # Make sure that the client knows how to talk to the server.
+    # "http://chef.example.com:4000" is part of the default config; if it's there,
+    # we can overwrite it
+    grep -q '^\s*chef_server_url\s*"http://chef.example.com:4000"' /etc/chef/client.rb 2> /dev/null
+    if [[ $? -eq 0 || ! -f /etc/chef/chef.rb ]]; then
+        test -f /etc/chef/chef.rb && mv /etc/chef/chef.rb /etc/chef/chef.rb.bak
+        echo "chef_server_url \"http://$IP:4000\"" >/etc/chef/client.rb
+
+        # add reboot handler to chef-client
+        # FIXME: there is a cleaner way of adding handlers:
+        # http://wiki.opscode.com/display/chef/Opscode+LWRP+Resources#OpscodeLWRPResources-chefhandler
+
+        cat >> /etc/chef/client.rb <<EOF
+require "/var/chef/handlers/reboot_handler"
+reboot_handler = RebootHandler.new
+report_handlers << reboot_handler # these fire at the end of a successful run
+EOF
+
+        # create reboot handler
+        mkdir -p /var/chef/handlers
+        cat > /var/chef/handlers/reboot_handler.rb <<EOF
+class RebootHandler < Chef::Handler
+  def report
+    if node.run_state[:reboot]
+      Chef::Log.info("Reboot requested through node.run_state[:reboot]")
+      system("/sbin/reboot")
+    end
+  end
+end
+EOF
+
+    fi # if [[ $? -eq 0 || ! -f /etc/chef/chef.rb ]]
+
+    if [[ ! -x /etc/init.d/chef-client ]]; then
+        # Install Chef
+        echo "Installing Chef..."
+
+        while ! log_to zypper zypper -n refresh ; do
+            echo "Failed to do zypper refresh, wait and try again"
+            sleep 10
+        done
+        while ! log_to zypper zypper -n install rubygem-chef ; do
+            echo "Failed to do zypper install, wait and try again"
+            sleep 10
+        done
+
+        log_to chef chkconfig -a chef-client
+    fi # if [[ ! -x /etc/init.d/chef-client ]]
+}
+
 # Spin while we wait for the interface to come up.
 echo "Waiting on our network interface to come up..."
 while ! ip addr | grep -v " lo" | grep -q "inet "
@@ -109,76 +171,14 @@ done
 # Get our hostname
 HOSTNAME=$(hostname -f)
 
-sync_time() {
-    # stop ntpd before we run ntpdate, and start it again afterwards.
-    service ntp stop
-    # Warning! Newer sntp releases use different options (e.g. the one
-    # on openSUSE 12.1
-    while ! sntp -P no -r $IP; do
-	echo "Waiting for NTP server"
-	sleep 1
-    done
-}
-
-echo "Synchronizing time (pass 1)" 
+echo "Synchronizing time (pass 1)"
 sync_time
 
 # Mark us as readying, and get our cert.
 post_state $HOSTNAME "readying"
 final_state="ready"
-mkdir -p /etc/chef
-curl -o /etc/chef/validation.pem \
-    "http://$HTTP_SERVER/validation.pem"
 
-# Make sure that the client knows how to talk to the server.
-# "http://chef.example.com:4000" is part of the default config; if it's there,
-# we can overwrite it
-grep -q '^\s*chef_server_url\s*"http://chef.example.com:4000"' /etc/chef/client.rb 2> /dev/null
-if [[ $? -eq 0 || ! -f /etc/chef/chef.rb ]]; then
-    test -f /etc/chef/chef.rb && mv /etc/chef/chef.rb /etc/chef/chef.rb.bak
-    echo "chef_server_url \"http://$IP:4000\"" >/etc/chef/client.rb
-
-    # add reboot handler to chef-client
-    # FIXME: there is a cleaner way of adding handlers:
-    # http://wiki.opscode.com/display/chef/Opscode+LWRP+Resources#OpscodeLWRPResources-chefhandler
-    
-    cat >> /etc/chef/client.rb <<EOF
-require "/var/chef/handlers/reboot_handler"
-reboot_handler = RebootHandler.new
-report_handlers << reboot_handler # these fire at the end of a successful run
-EOF
-
-    # create reboot handler
-    mkdir -p /var/chef/handlers
-    cat > /var/chef/handlers/reboot_handler.rb <<EOF
-class RebootHandler < Chef::Handler
-  def report
-    if node.run_state[:reboot]
-      Chef::Log.info("Reboot requested through node.run_state[:reboot]")
-      system("/sbin/reboot")
-    end
-  end  
-end    
-EOF
-
-fi
-
-if [[ ! -x /etc/init.d/chef-client ]]; then
-    # Install Chef
-    echo "Installing Chef..."
-
-    while ! log_to zypper zypper -n refresh ; do
-	echo "Failed to do zypper refresh, wait and try again"
-	sleep 10
-    done
-    while ! log_to zypper zypper -n install rubygem-chef ; do
-	echo "Failed to do zypper install, wait and try again"
-	sleep 10
-    done
-
-    log_to chef chkconfig -a chef-client
-fi
-
+do_setup
 
 # Run Chef
 echo "Syncing time (pass 2)"
@@ -206,7 +206,7 @@ if ! log_to chef chef-client -l debug; then
     echo "Removing Chef Cache"
     rm -rf /var/cache/chef/*
     echo "Running Chef Client (pass 3) - cache cleanup"
-    if ! log_to chef chef-client -l debug; then 
+    if ! log_to chef chef-client -l debug; then
         log_to ifup /sbin/service network restart
         echo "Error Path"
         echo "Syncing Time (pass 4)"
@@ -217,7 +217,7 @@ if ! log_to chef chef-client -l debug; then
         rm -f /etc/chef/client.pem
         post_state $HOSTNAME "installed"
         echo "Running Chef Client (pass 4) - password cleanup"
-        if ! log_to chef chef-client -l debug; then 
+        if ! log_to chef chef-client -l debug; then
             log_to ifup /sbin/service network restart
             echo "chef-client run failed four times, giving up."
             echo "Failed"
