crowbar_join: Add two modes: setup and start
The setup mode is used for the initial setup done by crowbar_join.

The start mode will be used for later boots of the node, where setup is
not needed anymore.

diff --git a/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb b/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
--- a/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
+++ b/chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
@@ -216,6 +216,61 @@ do_chef_client() {
 }
 
 
+################## Option handling ##################
+
+SCRIPT=`basename $0`
+
+usage() {
+    echo "$SCRIPT -- Synchronize with Crowbar administration server"
+    echo ""
+    echo "Usage:"
+    echo "$SCRIPT [--setup|--start]"
+}
+
+ARGS=`getopt -o "h:" -l "help,setup,start" -n "$SCRIPT" -- "$@"`
+if test $? -ne 0; then
+   usage
+   exit 1
+fi
+
+eval set -- "$ARGS"
+
+MODE=
+
+while true; do
+    case "$1" in
+        --)
+            break
+            ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        --setup)
+            if test -n "$MODE"; then
+                echo "Error: more than one mode specified."
+                exit 1
+            fi
+            MODE="setup"
+            shift
+            ;;
+        --start)
+            if test -n "$MODE"; then
+                echo "Error: more than one mode specified."
+                exit 1
+            fi
+            MODE="start"
+            shift
+            ;;
+    esac
+done
+
+if test -z "$MODE"; then
+    echo "Error: no mode specified."
+    exit 1
+fi
+
+
 ################## Core ##################
 
 # This is required if the autoyast.xml had any <media_url> elements
@@ -233,35 +288,37 @@ fi
 
 CHEF_CLIENT_OPTIONS="-l debug"
 
-wait_for_network
-wait_for_hostname
+if [ "$MODE" == "setup" -o "$MODE" == "start" ]; then
+    wait_for_network
+    wait_for_hostname
 
-# Get our hostname
-HOSTNAME=$(hostname -f)
+    # Get our hostname
+    HOSTNAME=$(hostname -f)
 
-echo "Synchronizing time (pass 1)"
-sync_time
+    echo "Synchronizing time (pass 1)"
+    sync_time
 
-# Mark us as readying, and get our cert.
-post_state $HOSTNAME "readying"
-final_state="ready"
+    # Mark us as readying, and get our cert.
+    post_state $HOSTNAME "readying"
+    final_state="ready"
 
-do_setup
+    [ "$MODE" == "setup" ] && do_setup
 
-# Run Chef
-echo "Syncing time (pass 2)"
-sync_time
+    # Run Chef
+    echo "Syncing time (pass 2)"
+    sync_time
 
-do_chef_client_after_setup
-do_chef_client
+    [ "$MODE" == "setup" ] && do_chef_client_after_setup
+    do_chef_client
 
-# Transition to our final state
-post_state $HOSTNAME "$final_state"
+    # Transition to our final state
+    post_state $HOSTNAME "$final_state"
 
-# make sure to keep hostname
-echo $HOSTNAME > /etc/HOSTNAME
+    # make sure to keep hostname
+    [ "$MODE" == "setup" ] && echo $HOSTNAME > /etc/HOSTNAME
 
-log_to time service ntp start
-service chef-client start
+    log_to time service ntp start
+    [ "$MODE" == "setup" ] && log_to chef service chef-client start
+fi # setup or start
 
 echo "Done"
